import jsPDF from 'jspdf';
import 'jspdf-autotable';

interface EvalData { [key: string]: any; }
interface KPIEntry { category: string; custom_title: string | null; employee_rating: number | null; manager_rating: number | null; employee_comment: string | null; manager_comment: string | null; }

const RATING_LABELS = ['Very Poor', 'Poor', 'Fairly Good', 'Good', 'Excellent', 'Exceptional'];

function addHeader(doc: jsPDF, y: number): number {
  doc.setFontSize(14);
  doc.setFont('helvetica', 'bold');
  doc.text('Employee Performance Evaluation Form', 105, y, { align: 'center' });
  y += 8;
  doc.setDrawColor(100);
  doc.line(20, y, 190, y);
  return y + 6;
}

function addField(doc: jsPDF, label: string, value: string, x: number, y: number, w = 75): number {
  doc.setFontSize(8);
  doc.setFont('helvetica', 'bold');
  doc.text(label + ':', x, y);
  doc.setFont('helvetica', 'normal');
  doc.text(value || '—', x + w * 0.45, y);
  return y;
}

function addWatermark(doc: jsPDF, text: string) {
  const pages = doc.internal.pages.length - 1;
  for (let i = 1; i <= pages; i++) {
    doc.setPage(i);
    doc.setFontSize(48);
    doc.setTextColor(100, 100, 100);
    doc.setGState(new (doc as any).GState({ opacity: 0.15 }));
    doc.text(text, 105, 160, { align: 'center', angle: 45 });
    doc.setGState(new (doc as any).GState({ opacity: 1 }));
    doc.setTextColor(0, 0, 0);
  }
}

function addFooter(doc: jsPDF) {
  const pages = doc.internal.pages.length - 1;
  for (let i = 1; i <= pages; i++) {
    doc.setPage(i);
    doc.setFontSize(7);
    doc.setTextColor(120);
    doc.text('Generated by Staff Appraisal System', 20, 285);
    doc.text(`Page ${i} of ${pages}`, 105, 285, { align: 'center' });
    doc.text(new Date().toLocaleString(), 190, 285, { align: 'right' });
  }
}

export function generateEvaluationPDF(
  evaluation: EvalData,
  employee: EvalData,
  kpiEntries: KPIEntry[],
  manager?: EvalData | null,
) {
  const doc = new jsPDF('p', 'mm', 'a4');
  let y = 25;

  y = addHeader(doc, y);

  // Job Role
  doc.setFontSize(10);
  doc.setFont('helvetica', 'normal');
  doc.text(`Job Role: ${employee.function_role || employee.job_title || '—'}`, 20, y);
  y += 8;

  // Intro paragraph
  doc.setFontSize(7);
  doc.setFont('helvetica', 'bold');
  doc.text('General Information:', 20, y);
  y += 5;
  doc.setFont('helvetica', 'normal');
  const intro = 'The performance appraisal form constitutes four sets of key performance indicators (KPIs) including Primary KPIs A1, Primary KPI A2 (WIG), Secondary KPIs, and Generic KPIs. Each KPI has a maximum score of 6 with a scale from 0 to 5.';
  const lines = doc.splitTextToSize(intro, 170);
  doc.text(lines, 20, y);
  y += lines.length * 3.5 + 4;

  // Personal Info Table
  const longevity = employee.date_joining ? (() => {
    const join = new Date(employee.date_joining);
    const now = new Date();
    const months = (now.getFullYear() - join.getFullYear()) * 12 + now.getMonth() - join.getMonth();
    const yr = Math.floor(months / 12);
    const mo = months % 12;
    return yr > 0 ? `${yr}y ${mo}m` : `${months}m`;
  })() : '—';

  const infoRows = [
    ['Full name', employee.full_name || '—', 'Function', employee.function_role || '—'],
    ['Occupied since', employee.occupied_since || '—', 'Service/Unit', employee.department || '—'],
    ['Longevity', longevity, 'Qualification', employee.academic_qualification || '—'],
    ['Sex', employee.sex || '—', 'Marital Status', employee.marital_status || '—'],
    ['Evaluation Period', `${evaluation.cycle_id ? new Date().getFullYear() : '—'}`, 'Employee Type', evaluation.employee_type || '—'],
  ];

  (doc as any).autoTable({
    startY: y,
    head: [],
    body: infoRows,
    theme: 'grid',
    styles: { fontSize: 7, cellPadding: 1.5 },
    columnStyles: { 0: { fontStyle: 'bold', cellWidth: 30 }, 1: { cellWidth: 55 }, 2: { fontStyle: 'bold', cellWidth: 30 }, 3: { cellWidth: 55 } },
    margin: { left: 20, right: 20 },
  });
  y = (doc as any).lastAutoTable.finalY + 6;

  // KPI sections
  const categories = [
    { key: 'A1', label: 'Primary KPIs — A1' },
    { key: 'A2_WIG', label: 'Primary KPI A2 — WIG' },
    { key: 'secondary', label: 'Secondary KPIs' },
    { key: 'generic', label: 'Generic KPIs' },
  ];

  for (const cat of categories) {
    const entries = kpiEntries.filter(e => e.category === cat.key);
    if (entries.length === 0) continue;

    if (y > 250) { doc.addPage(); y = 20; }

    doc.setFontSize(9);
    doc.setFont('helvetica', 'bold');
    doc.text(cat.label, 20, y);
    y += 5;

    const kpiRows = entries.map(e => [
      e.custom_title || '—',
      e.employee_rating != null ? String(e.employee_rating) : '—',
      e.manager_rating != null ? String(e.manager_rating) : '—',
      e.employee_comment?.slice(0, 60) || '—',
    ]);

    (doc as any).autoTable({
      startY: y,
      head: [['KPI Title', 'Emp Rating', 'Mgr Rating', 'Comment']],
      body: kpiRows,
      theme: 'striped',
      styles: { fontSize: 7, cellPadding: 1.5 },
      headStyles: { fillColor: [30, 41, 59], textColor: [241, 245, 249], fontSize: 7 },
      columnStyles: { 0: { cellWidth: 65 }, 1: { cellWidth: 20, halign: 'center' }, 2: { cellWidth: 20, halign: 'center' }, 3: { cellWidth: 65 } },
      margin: { left: 20, right: 20 },
    });
    y = (doc as any).lastAutoTable.finalY + 4;

    // Score line
    doc.setFontSize(7);
    doc.setFont('helvetica', 'normal');
    if (cat.key === 'A1') doc.text(`A1 weighted: ${evaluation.a1_weighted?.toFixed(2) || '—'}`, 20, y);
    if (cat.key === 'A2_WIG') doc.text(`A2 weighted: ${evaluation.a2_weighted?.toFixed(2) || '—'}`, 20, y);
    if (cat.key === 'secondary') doc.text(`Secondary weighted: ${evaluation.sec_weighted?.toFixed(2) || '—'}`, 20, y);
    if (cat.key === 'generic') doc.text(`Generic weighted: ${evaluation.gen_weighted?.toFixed(2) || '—'}`, 20, y);
    y += 6;
  }

  // Final Score
  if (y > 250) { doc.addPage(); y = 20; }
  doc.setFontSize(11);
  doc.setFont('helvetica', 'bold');
  doc.text(`Total Appraisal Score: ${evaluation.final_score?.toFixed(2) || '—'} / 100`, 20, y);
  y += 5;
  doc.setFontSize(9);
  doc.text(`Classification: ${evaluation.final_classification || '—'}`, 20, y);
  y += 8;

  // Classification table
  const classTable = [
    ['00–35%', 'Very Poor'], ['36–49%', 'Poor'], ['50–65%', 'Fairly Good'],
    ['66–80%', 'Good'], ['81–95%', 'Excellent'], ['≥ 96%', 'Exceptional'],
  ];
  (doc as any).autoTable({
    startY: y, head: [['Range', 'Classification']], body: classTable,
    theme: 'grid', styles: { fontSize: 7, cellPadding: 1.5 },
    headStyles: { fillColor: [30, 41, 59], textColor: [241, 245, 249] },
    margin: { left: 20, right: 100 },
  });
  y = (doc as any).lastAutoTable.finalY + 8;

  // Page 2 - Additional sections
  doc.addPage();
  y = 20;

  // Career path
  doc.setFontSize(9);
  doc.setFont('helvetica', 'bold');
  doc.text('Preferred career path:', 20, y);
  y += 5;
  doc.setFont('helvetica', 'normal');
  doc.setFontSize(8);
  const cp = Array.isArray(evaluation.career_path) ? evaluation.career_path : [];
  if (cp.length > 0) cp.forEach((c: string) => { doc.text(`• ${c}`, 24, y); y += 4; });
  else { doc.text('—', 24, y); y += 4; }
  y += 4;

  // Training needs
  doc.setFontSize(9);
  doc.setFont('helvetica', 'bold');
  doc.text('Training needs:', 20, y);
  y += 5;
  doc.setFont('helvetica', 'normal');
  doc.setFontSize(8);
  const tn = Array.isArray(evaluation.training_needs) ? evaluation.training_needs : [];
  if (tn.length > 0) tn.forEach((t: string) => { doc.text(`• ${t}`, 24, y); y += 4; });
  else { doc.text('—', 24, y); y += 4; }
  y += 4;

  // Key areas
  doc.setFontSize(9);
  doc.setFont('helvetica', 'bold');
  doc.text('Key Areas that require improvement:', 20, y);
  y += 5;
  doc.setFont('helvetica', 'normal');
  doc.setFontSize(8);
  const kaLines = doc.splitTextToSize(evaluation.key_areas_improvement || '—', 170);
  doc.text(kaLines, 20, y);
  y += kaLines.length * 3.5 + 6;

  // Action plan
  doc.setFontSize(9);
  doc.setFont('helvetica', 'bold');
  doc.text('Proposed plan of action:', 20, y);
  y += 5;
  doc.setFont('helvetica', 'normal');
  doc.setFontSize(8);
  const apLines = doc.splitTextToSize(evaluation.proposed_action_plan || '—', 170);
  doc.text(apLines, 20, y);
  y += apLines.length * 3.5 + 8;

  // Remarks sections
  const remarksBlocks = [
    { label: 'Remarks/recommendations of first line manager', text: evaluation.first_manager_remarks, name: manager?.full_name, date: evaluation.first_manager_reviewed_at },
    { label: 'Comments of the employee', text: evaluation.employee_comments },
    { label: 'Remarks of second line manager', text: evaluation.second_manager_remarks },
    { label: 'Remarks/recommendations of HC', text: evaluation.hc_remarks },
    { label: 'Management action', text: evaluation.management_action },
  ];

  for (const block of remarksBlocks) {
    if (y > 250) { doc.addPage(); y = 20; }
    doc.setFontSize(9);
    doc.setFont('helvetica', 'bold');
    doc.text(block.label + ':', 20, y);
    y += 5;
    doc.setFont('helvetica', 'normal');
    doc.setFontSize(8);
    const txt = doc.splitTextToSize(block.text || '(not filled)', 170);
    doc.text(txt, 20, y);
    y += txt.length * 3.5 + 2;
    if (block.name) { doc.text(`— ${block.name}`, 20, y); y += 4; }
    doc.text('Signature: _______________    Date: _____________    Name: _________________', 20, y);
    y += 8;
  }

  // Watermark for non-archived
  if (evaluation.status !== 'archived') {
    addWatermark(doc, 'DRAFT — NOT FINAL');
  }

  addFooter(doc);

  // Save
  const lastName = (employee.full_name || 'Unknown').split(' ').pop();
  const firstName = (employee.full_name || 'Unknown').split(' ')[0];
  const year = new Date().getFullYear();
  doc.save(`Appraisal_${lastName}_${firstName}_${year}.pdf`);
}
