import { User, EvaluationForm, AuditLogEntry } from '@/types/evaluation';

export const MOCK_USERS: User[] = [
  {
    id: 'u1',
    fullName: 'Sarah Chen',
    email: 'sarah.chen@bank.com',
    department: 'Information Technology',
    unit: 'Cybersecurity',
    jobTitle: 'Senior Security Analyst',
    managerId: 'u2',
    managerName: 'James Okafor',
    role: 'employee',
    longevity: '4 years',
    qualification: 'MSc Computer Science',
    maritalStatus: 'Married',
  },
  {
    id: 'u2',
    fullName: 'James Okafor',
    email: 'james.okafor@bank.com',
    department: 'Information Technology',
    unit: 'Cybersecurity',
    jobTitle: 'Head of Cybersecurity',
    managerId: 'u4',
    managerName: 'Admin User',
    role: 'manager',
    longevity: '8 years',
    qualification: 'MSc Information Security',
    maritalStatus: 'Married',
  },
  {
    id: 'u3',
    fullName: 'Amina Bello',
    email: 'amina.bello@bank.com',
    department: 'Human Resources',
    unit: 'Performance Management',
    jobTitle: 'HR Business Partner',
    managerId: 'u4',
    managerName: 'Admin User',
    role: 'hr',
    longevity: '6 years',
    qualification: 'MBA Human Resources',
    maritalStatus: 'Single',
  },
  {
    id: 'u4',
    fullName: 'Admin User',
    email: 'admin@bank.com',
    department: 'Administration',
    unit: 'System Administration',
    jobTitle: 'System Administrator',
    managerId: '',
    managerName: '',
    role: 'admin',
    longevity: '10 years',
    qualification: 'BSc Computer Science',
    maritalStatus: 'Married',
  },
];

export const MOCK_EVALUATIONS: EvaluationForm[] = [
  {
    id: 'ev1',
    employeeId: 'u1',
    employeeName: 'Sarah Chen',
    department: 'Information Technology',
    unit: 'Cybersecurity',
    jobTitle: 'Senior Security Analyst',
    longevity: '4 years',
    qualification: 'MSc Computer Science',
    maritalStatus: 'Married',
    evaluationYear: 2024,
    isSalesStaff: false,
    primaryA1: [
      { id: 'k1', title: 'Vulnerability Assessment & Penetration Testing', rating: 4, comment: 'Consistently identified critical vulnerabilities' },
      { id: 'k2', title: 'Incident Response Management', rating: 5, comment: 'Led 3 major incident responses successfully' },
      { id: 'k3', title: 'Security Policy Development', rating: 3, comment: 'Updated 5 security policies' },
      { id: 'k4', title: 'Threat Intelligence Analysis', rating: 4, comment: 'Proactive threat hunting initiatives' },
      { id: 'k5', title: 'Security Awareness Training', rating: 4, comment: 'Conducted 12 training sessions' },
    ],
    primaryA2: [
      { id: 'k6', title: 'Reduce security incidents by 30%', rating: 4, comment: 'Achieved 28% reduction' },
    ],
    secondaryKPIs: [
      { id: 'k7', title: 'Cross-team Collaboration', rating: 4, comment: 'Strong collaboration with DevOps' },
      { id: 'k8', title: 'Documentation Quality', rating: 3, comment: 'Improved documentation standards' },
    ],
    genericKPIs: [
      { id: 'k9', title: 'Reporting', rating: 4, comment: 'Timely and accurate reports' },
      { id: 'k10', title: 'Teamwork', rating: 5, comment: 'Excellent team player' },
      { id: 'k11', title: 'Adaptability', rating: 4, comment: 'Quick to adopt new tools' },
    ],
    careerPathPreferences: 'Security Operations, Security Architecture',
    trainingNeeds: 'Cloud Security, Zero Trust Architecture',
    areasForImprovement: 'Presentation skills, Stakeholder management',
    proposedActionPlan: 'Enroll in public speaking course, Shadow senior management meetings',
    employeeComments: 'I am committed to growing in the cybersecurity domain.',
    managerRemarks: '',
    hrRemarks: '',
    status: 'submitted',
    totalScore: 78,
    classification: 'Good',
    createdAt: '2024-11-15T09:00:00Z',
    updatedAt: '2024-12-01T14:30:00Z',
    submittedAt: '2024-12-01T14:30:00Z',
  },
  {
    id: 'ev2',
    employeeId: 'u1',
    employeeName: 'Sarah Chen',
    department: 'Information Technology',
    unit: 'Cybersecurity',
    jobTitle: 'Security Analyst',
    longevity: '3 years',
    qualification: 'MSc Computer Science',
    maritalStatus: 'Married',
    evaluationYear: 2023,
    isSalesStaff: false,
    primaryA1: [
      { id: 'k12', title: 'Vulnerability Scanning', rating: 3, comment: '' },
      { id: 'k13', title: 'Log Analysis', rating: 4, comment: '' },
      { id: 'k14', title: 'Security Monitoring', rating: 3, comment: '' },
      { id: 'k15', title: 'Compliance Checks', rating: 3, comment: '' },
      { id: 'k16', title: 'Patch Management', rating: 4, comment: '' },
    ],
    primaryA2: [
      { id: 'k17', title: 'Implement SIEM solution', rating: 3, comment: '' },
    ],
    secondaryKPIs: [
      { id: 'k18', title: 'Knowledge Sharing', rating: 3, comment: '' },
      { id: 'k19', title: 'Process Improvement', rating: 3, comment: '' },
    ],
    genericKPIs: [
      { id: 'k20', title: 'Reporting', rating: 3, comment: '' },
      { id: 'k21', title: 'Teamwork', rating: 4, comment: '' },
      { id: 'k22', title: 'Adaptability', rating: 3, comment: '' },
    ],
    careerPathPreferences: 'Security Operations',
    trainingNeeds: 'CISSP Certification',
    areasForImprovement: 'Technical writing',
    proposedActionPlan: 'Take technical writing course',
    employeeComments: '',
    managerRemarks: 'Solid performance. Ready for senior role.',
    hrRemarks: 'Validated.',
    status: 'validated',
    totalScore: 65,
    classification: 'Fairly Good',
    createdAt: '2023-11-10T09:00:00Z',
    updatedAt: '2024-01-15T10:00:00Z',
    submittedAt: '2023-12-01T14:00:00Z',
    approvedAt: '2024-01-10T09:00:00Z',
  },
];

export const MOCK_AUDIT_LOG: AuditLogEntry[] = [
  { id: 'a1', evaluationId: 'ev1', action: 'Created', performedBy: 'Sarah Chen', performedByRole: 'employee', timestamp: '2024-11-15T09:00:00Z', details: 'Evaluation form created for 2024 cycle', ipAddress: '10.0.1.45' },
  { id: 'a2', evaluationId: 'ev1', action: 'Draft Saved', performedBy: 'Sarah Chen', performedByRole: 'employee', timestamp: '2024-11-20T11:30:00Z', details: 'Primary A1 KPIs completed', ipAddress: '10.0.1.45' },
  { id: 'a3', evaluationId: 'ev1', action: 'Submitted', performedBy: 'Sarah Chen', performedByRole: 'employee', timestamp: '2024-12-01T14:30:00Z', details: 'Evaluation submitted for manager review', ipAddress: '10.0.1.45' },
  { id: 'a4', evaluationId: 'ev2', action: 'Approved', performedBy: 'James Okafor', performedByRole: 'manager', timestamp: '2024-01-10T09:00:00Z', details: 'Evaluation approved by line manager', ipAddress: '10.0.2.12' },
  { id: 'a5', evaluationId: 'ev2', action: 'Validated', performedBy: 'Amina Bello', performedByRole: 'hr', timestamp: '2024-01-15T10:00:00Z', details: 'Evaluation validated and archived by HR', ipAddress: '10.0.3.8' },
];

export const GENERIC_KPI_TEMPLATES = [
  'Reporting',
  'Teamwork',
  'Adaptability',
  'Communication',
  'Innovation',
  'Leadership',
  'Time Management',
  'Problem Solving',
];

export const CAREER_PATH_OPTIONS = [
  'Security Operations',
  'Security Auditing',
  'Risk Management',
  'Compliance',
  'IT Governance',
  'Software Development',
  'Data Analytics',
  'Project Management',
];

export const TRAINING_OPTIONS = [
  'Hardware Security Module training',
  'IT Risk Management',
  'Project Management',
  'Database Security',
  'Cloud Security',
  'CISSP Certification',
  'Agile Methodology',
  'Data Science & Analytics',
];
